# Generated by Django 4.0.3 on 2022-03-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_glbmodels_age_remove_glbmodels_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glbmodels',
            name='case_alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
