# Generated by Django 4.0.3 on 2022-04-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='glbmodels',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.comment'),
        ),
    ]
