# Generated by Django 4.0.3 on 2022-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_glbmodels_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glbmodels',
            name='comments',
        ),
        migrations.AddField(
            model_name='glbmodels',
            name='comments',
            field=models.ManyToManyField(null=True, to='viewer.comment'),
        ),
    ]
