# Generated by Django 4.0.3 on 2022-04-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_remove_glbmodels_comments_glbmodels_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glbmodels',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.glbmodels'),
        ),
    ]
