# Generated by Django 4.0.3 on 2022-04-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_remove_glbmodels_comments_comment_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='glbmodels',
            name='case_status',
            field=models.CharField(choices=[('1', 'PENDING'), ('2', 'Accepted'), ('3', 'Rejected')], default='1', max_length=100),
        ),
    ]
