# Generated by Django 4.0.3 on 2022-04-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_glbmodels_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glbmodels',
            name='case_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=100),
        ),
    ]
