# Generated by Django 4.0.3 on 2022-05-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_alter_glbmodels_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='glbmodels',
            name='lower_stages_number',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='glbmodels',
            name='upper_stages_number',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
