# Generated by Django 4.0.3 on 2022-12-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_glbmodels_lower_stages_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glbmodels',
            name='ipr_form',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
