# Generated by Django 3.2.5 on 2022-12-27 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_alter_comment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
