# Generated by Django 3.2.5 on 2022-12-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_alter_comment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glbmodels',
            name='ipr_form',
            field=models.ImageField(blank=True, default='media/ipr_gen.png', null=True, upload_to=''),
        ),
    ]
