# Generated by Django 3.2.5 on 2022-12-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_alter_glbmodels_ipr_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glbmodels',
            name='ipr_form',
            field=models.ImageField(blank=True, default='ipr_gen.png', null=True, upload_to=''),
        ),
    ]
